AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'tmp/*'
    - 'node_modules/**/*'

BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'
    - 'config/routes.rb'

LineLength:
  Enabled: true
  Max: 120

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

MethodLength:
  Enabled: true
  Max: 25

Style/BlockComments:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 20
